const NEGATIVE_TEST_REQUIRED = 'NEGATIVE_TEST_REQUIRED';
const NO_TEST_REQUIRED = 'NO_TEST_REQUIRED';
const QUARANTINE_REQUIRED = 'QUARANTINE_REQUIRED';

export const COUNTRY_TYPES = [NEGATIVE_TEST_REQUIRED, NO_TEST_REQUIRED, QUARANTINE_REQUIRED];
