export const CLOSED_BORDER = 'CLOSED_BORDER';
export const NEGATIVE_TEST_REQUIRED = 'NEGATIVE_TEST_REQUIRED';
export const NO_TEST_REQUIRED = 'NO_TEST_REQUIRED';
export const QUARANTINE_REQUIRED = 'QUARANTINE_REQUIRED';
export const VACCINATION_REQUIRED = 'VACCINATION_REQUIRED';

export const COUNTRY_LIST_LIMIT = 5;
