name: Github CI

on:
  push:
    branches:
      - master

jobs:
  lint-test-audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run lint

      - run: npm test

      - run: npm audit --audit-level=critical

  build-deploy:
    needs: lint-test-audit
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Github checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install, build and add the domain
        run: |
          npm ci
          npm run build
          npm run add-domain

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
